on: push

jobs:
    build:
        runs-on: ubuntu-latest
#        container: registry.gitlab.com/islandoftex/images/texlive:latest
        steps:
            - run: ls ${{ github.workspace }}
            - run: echo ${{ github.workspace }}
            - run: arara -lv "${{ github.workspace }}/Komunikacijska vezja in naprave"
#            
#            - name: Upload math result for job 1
#              uses: actions/upload-artifact@v3.1.1
#              with:
#                  name: homework
#                  path: ./*.pdf
