on: push

jobs:
    build:
        runs-on: ubuntu-latest
        container: registry.gitlab.com/islandoftex/images/texlive:latest
        steps:
            - run: apt update && apt install -y git
            - run: git clone https://github.com/Akaj-lab/Komunkacijska-vezja-in-naprave.git tmp
            - run: cd tmp
            - run: ls -la
            - run: pdflatex "Komunikacijska vezja in naprave.tex"
#            
#            - name: Upload math result for job 1
#              uses: actions/upload-artifact@v3.1.1
#              with:
#                  name: homework
#                  path: ./*.pdf
